/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as DocsWebsocketRouteImport } from './routes/docs/websocket'
import { Route as DocsUsersRouteImport } from './routes/docs/users'
import { Route as DocsSubgraphRouteImport } from './routes/docs/subgraph'
import { Route as DocsSmartContractsRouteImport } from './routes/docs/smart-contracts'
import { Route as DocsPaymentsRouteImport } from './routes/docs/payments'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsHandlersStorageRouteImport } from './routes/docs/handlers-storage'
import { Route as DocsAuthenticationRouteImport } from './routes/docs/authentication'
import { Route as DocsAgentsRouteImport } from './routes/docs/agents'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebsocketRoute = DocsWebsocketRouteImport.update({
  id: '/websocket',
  path: '/websocket',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsUsersRoute = DocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSubgraphRoute = DocsSubgraphRouteImport.update({
  id: '/subgraph',
  path: '/subgraph',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSmartContractsRoute = DocsSmartContractsRouteImport.update({
  id: '/smart-contracts',
  path: '/smart-contracts',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPaymentsRoute = DocsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsHandlersStorageRoute = DocsHandlersStorageRouteImport.update({
  id: '/handlers-storage',
  path: '/handlers-storage',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DocsRouteRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/waitlist': typeof WaitlistRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/handlers-storage': typeof DocsHandlersStorageRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/smart-contracts': typeof DocsSmartContractsRoute
  '/docs/subgraph': typeof DocsSubgraphRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/websocket': typeof DocsWebsocketRoute
  '/pay/$id': typeof PayIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/waitlist': typeof WaitlistRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/handlers-storage': typeof DocsHandlersStorageRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/smart-contracts': typeof DocsSmartContractsRoute
  '/docs/subgraph': typeof DocsSubgraphRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/websocket': typeof DocsWebsocketRoute
  '/pay/$id': typeof PayIdRoute
  '/agents': typeof AgentsIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/waitlist': typeof WaitlistRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/handlers-storage': typeof DocsHandlersStorageRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/smart-contracts': typeof DocsSmartContractsRoute
  '/docs/subgraph': typeof DocsSubgraphRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/websocket': typeof DocsWebsocketRoute
  '/pay/$id': typeof PayIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/dashboard'
    | '/marketplace'
    | '/onboarding'
    | '/settings'
    | '/waitlist'
    | '/agents/$agentId'
    | '/docs/agents'
    | '/docs/authentication'
    | '/docs/handlers-storage'
    | '/docs/installation'
    | '/docs/payments'
    | '/docs/smart-contracts'
    | '/docs/subgraph'
    | '/docs/users'
    | '/docs/websocket'
    | '/pay/$id'
    | '/agents/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/onboarding'
    | '/settings'
    | '/waitlist'
    | '/agents/$agentId'
    | '/docs/agents'
    | '/docs/authentication'
    | '/docs/handlers-storage'
    | '/docs/installation'
    | '/docs/payments'
    | '/docs/smart-contracts'
    | '/docs/subgraph'
    | '/docs/users'
    | '/docs/websocket'
    | '/pay/$id'
    | '/agents'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/dashboard'
    | '/marketplace'
    | '/onboarding'
    | '/settings'
    | '/waitlist'
    | '/agents/$agentId'
    | '/docs/agents'
    | '/docs/authentication'
    | '/docs/handlers-storage'
    | '/docs/installation'
    | '/docs/payments'
    | '/docs/smart-contracts'
    | '/docs/subgraph'
    | '/docs/users'
    | '/docs/websocket'
    | '/pay/$id'
    | '/agents/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  WaitlistRoute: typeof WaitlistRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  PayIdRoute: typeof PayIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/websocket': {
      id: '/docs/websocket'
      path: '/websocket'
      fullPath: '/docs/websocket'
      preLoaderRoute: typeof DocsWebsocketRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/users': {
      id: '/docs/users'
      path: '/users'
      fullPath: '/docs/users'
      preLoaderRoute: typeof DocsUsersRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/subgraph': {
      id: '/docs/subgraph'
      path: '/subgraph'
      fullPath: '/docs/subgraph'
      preLoaderRoute: typeof DocsSubgraphRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/smart-contracts': {
      id: '/docs/smart-contracts'
      path: '/smart-contracts'
      fullPath: '/docs/smart-contracts'
      preLoaderRoute: typeof DocsSmartContractsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/payments': {
      id: '/docs/payments'
      path: '/payments'
      fullPath: '/docs/payments'
      preLoaderRoute: typeof DocsPaymentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/handlers-storage': {
      id: '/docs/handlers-storage'
      path: '/handlers-storage'
      fullPath: '/docs/handlers-storage'
      preLoaderRoute: typeof DocsHandlersStorageRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsHandlersStorageRoute: typeof DocsHandlersStorageRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPaymentsRoute: typeof DocsPaymentsRoute
  DocsSmartContractsRoute: typeof DocsSmartContractsRoute
  DocsSubgraphRoute: typeof DocsSubgraphRoute
  DocsUsersRoute: typeof DocsUsersRoute
  DocsWebsocketRoute: typeof DocsWebsocketRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsAgentsRoute: DocsAgentsRoute,
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsHandlersStorageRoute: DocsHandlersStorageRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPaymentsRoute: DocsPaymentsRoute,
  DocsSmartContractsRoute: DocsSmartContractsRoute,
  DocsSubgraphRoute: DocsSubgraphRoute,
  DocsUsersRoute: DocsUsersRoute,
  DocsWebsocketRoute: DocsWebsocketRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  WaitlistRoute: WaitlistRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  PayIdRoute: PayIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
